import React from 'react';
import { useNavigate } from 'react-router-dom';
import './MySpace.css';

const watchlist = [
  { id: 101, title: 'Pulp Fiction', img: '/images/pulp-fiction.jpg' },
  { id: 102, title: 'Kill Bill', img: '/images/killbill.jpg' },
];

const MySpace = () => {
  const navigate = useNavigate();

  const user = {
    name: localStorage.getItem('userName') || "Jegan Vishnu",
    email: localStorage.getItem('userEmail') || "jegan.vishnu@zetflix.com",
    plan: "Premium Ultra HD",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jegan&backgroundColor=1E90FF",
    joinDate: "July 2026",
  };

  const handleLogout = () => {
    localStorage.removeItem('userEmail');
    navigate('/login');
  };

  const [uploadData, setUploadData] = React.useState({ title: '', description: '', img: '', year: '', certificate: '', genres: '' });
  const [uploadMessage, setUploadMessage] = React.useState('');

  const [isSearching, setIsSearching] = React.useState(false);

  const handleAutoFill = () => {
    if (!uploadData.title) {
      setUploadMessage('Please enter a Movie Title first!');
      setTimeout(() => setUploadMessage(''), 3000);
      return;
    }
    
    setIsSearching(true);
    
    // Simulate API/AI delay
    setTimeout(() => {
      const titleLower = uploadData.title.toLowerCase();
      
      // Mock AI Database
      const movieDB = {
        'inception': { img: 'https://images.unsplash.com/photo-1626814026160-2237a95fc5a0?w=500&q=80', year: '2010', certificate: 'PG-13', genres: 'Sci-Fi, Action, Thriller', description: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.' },
        'interstellar': { img: 'https://images.unsplash.com/photo-1618666012174-83b441c0bc76?w=500&q=80', year: '2014', certificate: 'PG-13', genres: 'Sci-Fi, Adventure, Drama', description: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.' },
        'the dark knight': { img: 'https://images.unsplash.com/photo-1533158326339-7f3cf2404354?w=500&q=80', year: '2008', certificate: 'PG-13', genres: 'Action, Crime, Drama', description: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.' },
        'avatar': { img: 'https://images.unsplash.com/photo-1574267432553-4b4628081524?w=500&q=80', year: '2009', certificate: 'PG-13', genres: 'Sci-Fi, Action, Adventure', description: 'A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.' }
      };

      const found = movieDB[titleLower];
      
      if (found) {
        setUploadData(prev => ({ ...prev, ...found }));
        setUploadMessage('✨ Details automatically filled by AI!');
      } else {
        // Generate random details if not found
        setUploadData(prev => ({
          ...prev,
          img: 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=500&q=80',
          year: Math.floor(Math.random() * (2026 - 1980 + 1) + 1980).toString(),
          certificate: ['PG', 'PG-13', 'R', 'A'][Math.floor(Math.random() * 4)],
          genres: 'Drama, Mystery',
          description: `An incredible cinematic journey exploring the mysteries behind "${uploadData.title}". Generated by AI.`
        }));
        setUploadMessage('✨ AI generated mock details for this unknown movie!');
      }
      
      setIsSearching(false);
      setTimeout(() => setUploadMessage(''), 4000);
    }, 800);
  };

  const [uploadProgress, setUploadProgress] = React.useState(null);

  const handleUpload = (e) => {
    e.preventDefault();
    if (!uploadData.title || !uploadData.img) {
      setUploadMessage('Title and Image URL are required!');
      return;
    }
    
    // Simulate upload progress
    setUploadProgress(0);
    const interval = setInterval(() => {
      setUploadProgress(prev => {
        if (prev >= 100) {
          clearInterval(interval);
          
          // Complete upload
          const existingUploads = JSON.parse(localStorage.getItem('uploadedMovies') || '[]');
          const newMovie = {
            id: Date.now(),
            title: uploadData.title,
            description: uploadData.description || 'A newly uploaded movie.',
            imageUrl: uploadData.img,
            year: uploadData.year || new Date().getFullYear().toString(),
            maturity: uploadData.certificate || 'PG-13',
            duration: '2h',
            tags: uploadData.genres ? uploadData.genres.split(',').map(g => g.trim()) : ['New', 'Upload']
          };
          
          localStorage.setItem('uploadedMovies', JSON.stringify([...existingUploads, newMovie]));
          setUploadData({ title: '', description: '', img: '', year: '', certificate: '', genres: '' });
          setUploadProgress(null);
          setUploadMessage('Movie uploaded successfully!');
          setTimeout(() => setUploadMessage(''), 3000);
          
          return null;
        }
        return prev + 10;
      });
    }, 200);
  };

  return (
    <div className="page-container myspace-page">
      <div className="profile-header">
        <div className="profile-avatar-container">
          <img src={user.avatar} alt="User Avatar" className="profile-avatar" />
          <button className="edit-avatar-btn">✎</button>
        </div>
        <div className="profile-info">
          <h2>{user.name}</h2>
          <p className="profile-email">{user.email}</p>
          <div className="profile-badges">
            <span className="badge plan-badge">★ {user.plan}</span>
            <span className="badge member-badge">Member since {user.joinDate}</span>
          </div>
        </div>
        <div className="profile-actions">
          <button className="manage-account-btn">Manage Account</button>
          <button className="logout-btn" onClick={handleLogout}>Log Out</button>
        </div>
      </div>

      <div className="myspace-content">
        <section className="myspace-section">
          <div className="section-header">
            <h3>My Watchlist</h3>
            <button className="view-all-btn">View All</button>
          </div>
          <div className="movies-grid">
            {watchlist.map(movie => (
              <div key={movie.id} className="movie-card">
                <div className="movie-card-img" style={{ backgroundImage: `url(${movie.img})` }}>
                  <div className="movie-card-overlay">
                    <button className="play-btn">▶</button>
                  </div>
                </div>
                <h4>{movie.title}</h4>
              </div>
            ))}
          </div>
        </section>

        <section className="myspace-section upload-section">
          <div className="section-header">
            <h3>Upload Movie</h3>
          </div>
          <div className="upload-container">
            <p className="upload-desc">Upload a movie to share it with everyone on the home page.</p>
            <form onSubmit={handleUpload} className="upload-form">
              <div className="title-search-container">
                <input 
                  type="text" 
                  placeholder="Movie Title" 
                  value={uploadData.title}
                  onChange={e => setUploadData({...uploadData, title: e.target.value})}
                  className="title-input"
                />
                <button type="button" className="ai-search-btn" onClick={handleAutoFill} disabled={isSearching}>
                  {isSearching ? 'Searching...' : 'Search Details 🔍'}
                </button>
              </div>
              <input 
                type="text" 
                placeholder="Image URL (e.g. https://...)" 
                value={uploadData.img}
                onChange={e => setUploadData({...uploadData, img: e.target.value})}
              />
              <input 
                type="text" 
                placeholder="Year (e.g. 2026)" 
                value={uploadData.year}
                onChange={e => setUploadData({...uploadData, year: e.target.value})}
              />
              <input 
                type="text" 
                placeholder="Movie Certificate (e.g. PG-13, R)" 
                value={uploadData.certificate}
                onChange={e => setUploadData({...uploadData, certificate: e.target.value})}
              />
              <input 
                type="text" 
                placeholder="Genres (comma separated, e.g. Action, Drama)" 
                value={uploadData.genres}
                onChange={e => setUploadData({...uploadData, genres: e.target.value})}
              />
              <textarea 
                placeholder="Full Description" 
                value={uploadData.description}
                onChange={e => setUploadData({...uploadData, description: e.target.value})}
                className="full-desc-textarea"
                rows="4"
              />
              <div className="file-upload-container">
                <label className="file-upload-label">
                  Movie File
                  <input type="file" accept="video/*" className="file-input" />
                </label>
                <div className="or-divider">or</div>
                <input 
                  type="text" 
                  placeholder="Paste Video Link here (e.g. https://...)" 
                  className="link-input"
                  value={uploadData.videoLink || ''}
                  onChange={e => setUploadData({...uploadData, videoLink: e.target.value})}
                />
              </div>
              
              {uploadProgress !== null && (
                <div className="progress-bar-container">
                  <div className="progress-bar-fill" style={{ width: `${uploadProgress}%` }}></div>
                  <span className="progress-text">{uploadProgress}% Uploading...</span>
                </div>
              )}
              
              <button type="submit" className="setting-action upload-submit-btn" disabled={uploadProgress !== null}>
                {uploadProgress !== null ? 'Uploading...' : 'Upload'}
              </button>
            </form>
            {uploadMessage && <p className="upload-msg">{uploadMessage}</p>}
          </div>
        </section>

        <section className="myspace-section">
          <div className="section-header">
            <h3>Account Settings</h3>
          </div>
          <div className="settings-grid">
            <div className="setting-card">
              <span className="setting-icon">🔒</span>
              <div className="setting-details">
                <h4>Password & Security</h4>
                <p>Update your password and secure your account</p>
              </div>
              <button className="setting-action">Update</button>
            </div>

            <div className="setting-card">
              <span className="setting-icon">📺</span>
              <div className="setting-details">
                <h4>Playback Settings</h4>
                <p>Data usage, autoplay, and video quality</p>
              </div>
              <button className="setting-action">Edit</button>
            </div>
          </div>
        </section>
      </div>
    </div>
  );
};

export default MySpace;
